### ISSUE TITLE
HOST HOME dir not automounted!!!

### ISSUE THREAD

**Issue by ashcoll** [boot2docker/boot2docker#1400] opened 2019-08-12 10:24 UTC
according to DOC, host home dir will auto mount to vm , but not !!!

### version
1. docker-machine version 0.16.1, build cce350d7
1. boot2docker: v19.03.1
1. host: linux kernel-4.19.57

### bug
Command: `docker-machine create -d virtualbox test-vm1`

`docker-machine ssh test-vm1`

1. according to DOC，`home` will auto mount, but not!
2. use docker-machine mount：issue - You must have a copy of the `sshfs` binary locally to use the mount feature!

**Does `sshfs` affect `home` dir auto mount?**

**Comment by tianon** [comment] 2019-08-12 15:50
Duplicate of #1398

**Closed by tianon** 2019-08-12 15:50 UTC
