### ISSUE TITLE
Why is ipv6 disabled in boot2docker 17.04?

### ISSUE THREAD

**Issue by davidxia** [boot2docker/boot2docker#1257] opened 2017-05-02 19:34 UTC
I'm trying to run unbound in a container (`docker run -it --entrypoint=/bin/bash spotify/helios-solo:latest` to be exact). One of the ports it listens to is `::1 8953`. `unbound` starts fine with boot2docker 17.03 and below, but it fails on 17.04.

```
root@b830b961e530:/# unbound
[1493753376] unbound[107:0] debug: creating udp4 socket 0.0.0.0 53
[1493753376] unbound[107:0] debug: creating tcp4 socket 0.0.0.0 53
[1493753376] unbound[107:0] debug: creating udp6 socket :: 53
[1493753376] unbound[107:0] debug: creating tcp6 socket :: 53
[1493753376] unbound[107:0] debug: creating tcp6 socket ::1 8953
[1493753376] unbound[107:0] error: can't bind socket: Cannot assign requested address
[1493753376] unbound[107:0] debug: failed address ip6 ::1 port 8953 (len 28)
[1493753376] unbound[107:0] error: cannot open control interface ::1 8953
[1493753376] unbound[107:0] fatal error: could not open ports
```

This is because ipv6 is disabled for some reason.

```
root@b830b961e530:/# sysctl -a | grep disable_ipv6

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

Compare 17.03.

```
root@98c78f0fd9ce:/# sysctl -a | grep disable_ipv6

net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
```

Why the change? Was this intentional? Could we re-enable ipv6 by updating [sysctl.conf](https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/sysctl.conf)?

**Comment by yosifkit** [comment] 2017-05-02 23:38
This is not a change within boot2docker, but, as far as I can tell, a ~"feature"~ regression of the 17.04.0-ce docker release ([release notes](https://github.com/moby/moby/releases/tag/v17.04.0-ce)).  I can only guess that it seems to be related to https://github.com/moby/moby/pull/30807, since it is the only one to mention ipv6, but I can't seem to figure out how to use `link-local-ip` to have it just generate one.

**Comment by thaJeztah** [comment] 2017-05-03 00:54
If you're running containers with `--network=host`, this is most likely due to a bug in docker 17.04; https://github.com/moby/moby/issues/32433, which will be fixed in 17.05 which is scheduled to be released soon

**Comment by davidxia** [comment] 2017-05-03 01:00
@thaJeztah Thanks for clarifying.

**Comment by davidxia** [comment] 2017-05-03 01:00
Feel free to close.

**Comment by thaJeztah** [comment] 2017-05-03 01:24
You're welcome! Oh, I don't have permissions on this repository to close issues, but you should be able to do so yourself 👍

**Closed** 2017-05-03 01:25 UTC
