### ISSUE TITLE
docker-machine create fails on MacOS with hdiutil: attach failed - no mountable file systems using v18.09.0

### ISSUE THREAD

**Issue by eriksette** [boot2docker/boot2docker#1365] opened 2018-11-28 17:40 UTC
Been working fine and today I am hitting this issue.
Sample of the docker-machine create:
$ docker-machine -D create --driver xhyve --engine-storage-driver overlay2 --xhyve-cpu-count -1 --xhyve-memory-size 6144 chat-manager
Docker Machine Version:  0.16.0, build 702c267f
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:49677
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:49683
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(chat-manager) Calling .GetMachineName
(chat-manager) Calling .DriverName
(chat-manager) Calling .GetCreateFlags
(chat-manager) Calling .SetConfigFromFlags
Reading certificate data from /Users/esette/.docker/machine/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /Users/esette/.docker/machine/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Running pre-create checks...
(chat-manager) Calling .PreCreateCheck
(chat-manager) DBG | ===== Docker Machine xhyve Driver Version 0.3.3 (Homebrew7d92f74) =====
(chat-manager) DBG |
(chat-manager) Calling .GetConfigRaw
Creating machine...
(chat-manager) Calling .Create
(chat-manager) DBG | local Boot2Docker ISO version:
(chat-manager) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(chat-manager) Latest release for github.com/boot2docker/boot2docker is v18.09.0
(chat-manager) Downloading /Users/esette/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.09.0/boot2docker.iso...
(chat-manager) DBG | Fix boot2docker.iso file permission...
(chat-manager) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(chat-manager) Copying /Users/esette/.docker/machine/cache/boot2docker.iso to /Users/esette/.docker/machine/machines/chat-manager/boot2docker.iso...
(chat-manager) Creating VM...
(chat-manager) DBG | Mounting boot2docker.iso
(chat-manager) DBG | executing: &{/usr/bin/hdiutil [hdiutil attach /Users/esette/.docker/machine/machines/chat-manager/boot2docker.iso -mountpoint /Users/esette/.docker/machine/machines/chat-manager/b2d-image] []  <nil> 0xc42000e018 0xc42000e020 [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>} attach /Users/esette/.docker/machine/machines/chat-manager/boot2docker.iso -mountpoint /Users/esette/.docker/machine/machines/chat-manager/b2d-image
(chat-manager) DBG | hdiutil: attach failed - no mountable file systems
Error creating machine: Error in driver during machine creation: exit status 1
notifying bugsnag: [Error creating machine: Error in driver during machine creation: exit status 1]

**Comment by tianon** [comment] 2018-11-28 20:36
Duplicate of https://github.com/boot2docker/boot2docker/issues/1355

**Closed by tianon** 2018-11-28 20:36 UTC
