### ISSUE TITLE
UEFI Support

### ISSUE THREAD

**Issue by haipengno1** [boot2docker/boot2docker#1404] opened 2019-11-18 11:36 UTC
VMware is starting to move to UEFI as the default option for new VMs and boot2docker currently does not boot in this mode. It isn't difficult to change the mode back to BIOS, but UEFI is definitely the way forward.
And Rancher os will supported in version 1.6 as planned

**Comment by tianon** [comment] 2019-11-18 21:03
Technically a duplicate of https://github.com/boot2docker/boot2docker/issues/1239.  I'd rather not support UEFI officially given this project's status (perhaps this will be what finally pushes folks to use a different distro like RancherOS instead of hanging onto the barely-on-life-support boot2docker).

As for the technical details, I couldn't help but play with this *a little*, but ultimately was not successful.  Here's my WIP in case someone else wants to play in their own fork and thinks they can figure out what I did wrong: :smile: :+1:

<details>
<summary>Diff:</summary>

```diff
diff --git a/Dockerfile b/Dockerfile
index 556192d..a2429c3 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -523,11 +523,13 @@ RUN savedAptMark="$(apt-mark showmanual)"; \
 	apt-get install -y --no-install-recommends \
 		isolinux \
 		syslinux-common \
+		syslinux-efi \
 	; \
 	rm -rf /var/lib/apt/lists/*; \
 	mkdir -p /tmp/iso/isolinux; \
 	cp -v \
 		/usr/lib/ISOLINUX/isolinux.bin \
+		/usr/lib/SYSLINUX.EFI/efi64/syslinux.efi \
 		/usr/lib/syslinux/modules/bios/ldlinux.c32 \
 		/usr/lib/syslinux/modules/bios/libutil.c32 \
 		/usr/lib/syslinux/modules/bios/menu.c32 \
diff --git a/files/make-b2d-iso.sh b/files/make-b2d-iso.sh
index 2c058cc..8e19c29 100755
--- a/files/make-b2d-iso.sh
+++ b/files/make-b2d-iso.sh
@@ -16,9 +16,12 @@ xorriso \
 	-isohybrid-mbr /tmp/isohdpfx.bin \
 	-b isolinux/isolinux.bin \
 	-c isolinux/boot.cat \
+	-isohybrid-gpt-basdat \
+	-e isolinux/syslinux.efi \
 	-no-emul-boot \
 	-boot-load-size 4 \
 	-boot-info-table \
+	-eltorito-alt-boot \
 	/tmp/iso
 
 mkdir -p /tmp/stats
````

</details>

**Closed by tianon** 2019-11-18 21:03 UTC
