### ISSUE TITLE
boot2docker up sometimes hangs with 1.5.0-rc1

### ISSUE THREAD

**Issue by proppy** [boot2docker/boot2docker#713] opened 2015-01-26 22:33 UTC
It is not consistent, but sometime `boot2docker up` with 1.5.0-rc1 (mentioned in https://github.com/docker/docker/pull/10286) hangs because of what appear to be some weird docker daemon startup state, see:
```
/usr/local/google/home/proppy$ boot2docker up
Waiting for VM and Docker daemon to start...
.....................oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo^C
```

daemon logs below:
```
------------------------
/usr/local/bin/docker -d -D -g "/var/lib/docker" -H unix:// -H tcp://0.0.0.0:2376  --tlsverify --tlscacert=/var/lib/boot2docker/tls/ca.pem --tlscert=/var/lib/boot2docker/tls/server.pem --tlskey=/var/lib/boot2docker/tls/serverkey.pem >> "/var/lib/boot2docker/docker.log"
time="2015-01-26T22:30:22Z" level="info" msg="+job serveapi(unix:///var/run/docker.sock, tcp://0.0.0.0:2376)" 
time="2015-01-26T22:30:23Z" level="info" msg="Listening for HTTP on unix (/var/run/docker.sock)" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /_ping" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/attach/ws" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /version" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/ps" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/changes" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /events" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/search" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/get" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/get" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/history" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/export" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /info" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/viz" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/manifest" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/top" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/logs" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/stats" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /exec/{id:.*}/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /auth" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /exec/{name:.*}/start" 
time="2015-01-26T22:30:23Z" level="info" msg="Listening for HTTP on tcp (0.0.0.0:2376)" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/ps" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/changes" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /version" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/search" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/get" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/get" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/history" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/export" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /events" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/viz" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/manifest" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/top" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/logs" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/stats" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /exec/{id:.*}/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /info" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /images/{name:.*}/json" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /containers/{name:.*}/attach/ws" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering GET, /_ping" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/create" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/load" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/{name:.*}/push" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/{name:.*}/tag" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/pause" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/rename" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /commit" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/restart" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /exec/{name:.*}/resize" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/unpause" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/kill" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/start" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/stop" 
time="2015-01-26T22:30:23Z" level="debug" msg="Using graph driver aufs" 
time="2015-01-26T22:30:23Z" level="debug" msg="Migrating existing containers" 
time="2015-01-26T22:30:23Z" level="debug" msg="Creating images graph" 
time="2015-01-26T22:30:23Z" level="debug" msg="Restored 0 elements" 
time="2015-01-26T22:30:23Z" level="debug" msg="Creating repository list" 
time="2015-01-26T22:30:23Z" level="info" msg="+job init_networkdriver()" 
time="2015-01-26T22:30:23Z" level="debug" msg="Creating bridge docker0 with network 172.17.42.1/16" 
time="2015-01-26T22:30:23Z" level="debug" msg="setting bridge mac address = true" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /exec/{name:.*}/resize" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/create" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/load" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/{name:.*}/push" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/start" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/rename" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /build" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/unpause" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/restart" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/wait" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/attach" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/copy" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/exec" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /commit" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /images/{name:.*}/tag" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/create" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/kill" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/pause" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/stop" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/resize" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering DELETE, /containers/{name:.*}" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering DELETE, /images/{name:.*}" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering OPTIONS, " 
time="2015-01-26T22:30:23Z" level="debug" msg="docker group found. gid: 100" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/resize" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/create" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /build" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/wait" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/attach" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/copy" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /containers/{name:.*}/exec" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /exec/{name:.*}/start" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering POST, /auth" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering DELETE, /containers/{name:.*}" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering DELETE, /images/{name:.*}" 
time="2015-01-26T22:30:23Z" level="debug" msg="Registering OPTIONS, " 
no such device
time="2015-01-26T22:30:23Z" level="info" msg="-job init_networkdriver() = ERR (1)" 
time="2015-01-26T22:30:23Z" level="fatal" msg="no such device" 
```

Let me know if I can get more detail?

**Comment by SvenDowideit** [comment] 2015-02-23 23:55
@proppy sorry - are you still seeing this?

when the cli is printing `o`'s, its trying to talk to the nat port forwarded ssh socket - so it can find out which port the Docker daemon is listening on.

I'd try to reproduce with `boot2docker -v` (or turn on the verbose option in the b2d profile file)

and I would look at the vbox network settings to see if they're 'normal' (ie that the vm's ssh is port forwarded to where your b2d thinks it should be)

lastly, try sshing to there using ssh - it should at least connect.

**Comment by proppy** [comment] 2015-02-27 06:58
Haven't see this issue recently.

**Comment by thedewi** [comment] 2015-03-04 06:44
I'm seeing this during most boots. Clean install of boot2docker v1.5.0 in Windows 7 with VirtualBox 4.3.22:
```
time="2015-03-04T06:29:14Z" level="debug" msg="docker group found. gid: 100"
no such device
time="2015-03-04T06:29:15Z" level="info" msg="-job init_networkdriver() = ERR (1)"
time="2015-03-04T06:29:15Z" level="fatal" msg="no such device"
```

#745 appears to be a duplicate of this issue.

@SvenDowideit, sometimes the ssh probe finds the pid & socket and returns success, only for the docker process to terminate moments later. ssh itself is working solidly. I've tried ```destroy```ing and re-```init```ing the virtualbox machine, but it still happens frequently.

**Closed** 2015-04-14 22:18 UTC

**Comment by geeth4sg** [comment] 2015-05-09 05:43
Hi which port need to allow for aws instance.. docker started without any error (/var/log/docker)..

There is no response after run the below command

root@system:~# docker run -i -t vbatts/slackware bash

/var/lib/docker/devicemapper/ - has been created

root@system:~# tail -f /var/log/docker.log time="2015-05-09T05:17:31Z" level="info" msg="+job serveapi(unix:///var/run/docker.sock)" time="2015-05-09T05:17:31Z" level="info" msg="Listening for HTTP on unix (/var/run/docker.sock)"
