### ISSUE TITLE
Space in home directory

### ISSUE THREAD

**Issue by kraney** [boot2docker/boot2docker#768] opened 2015-03-01 16:44 UTC
On OSX, the command "boot2docker shellinit" is failing when my home directory path has a space in it.

tobenhaus-nb:~ kraney$  $(/usr/local/bin/boot2docker shellinit)
Writing /Volumes/600GB SSD/Users/kraney/.boot2docker/certs/boot2docker-vm/ca.pem
Writing /Volumes/600GB SSD/Users/kraney/.boot2docker/certs/boot2docker-vm/cert.pem
Writing /Volumes/600GB SSD/Users/kraney/.boot2docker/certs/boot2docker-vm/key.pem
bash: export: `SSD/Users/kraney/.boot2docker/certs/boot2docker-vm': not a valid identifier

**Comment by SvenDowideit** [comment] 2015-03-03 18:47
poking this too

**Comment by SvenDowideit** [comment] 2015-03-03 18:56
this is a duplicate of #715

**Closed by SvenDowideit** 2015-03-03 18:56 UTC
