### ISSUE TITLE
Boot2Docker stuck at Waiting as requested...

### ISSUE THREAD

**Issue by ncoop23** [boot2docker/boot2docker#1285] opened 2017-11-13 01:24 UTC
I've tried many things to get around this and have read a lot about the issue.  My configuration:
Windows 10 Pro 64.
i7 6700k
32 GB RAM
Hyper V
I cannot get the Boot2Docker VM running.  Logs posted below

```
PS C:\WINDOWS\system32> docker-machine create --driver hyperv vm
Running pre-create checks...
(vm) Image cache directory does not exist, creating it at C:\Users\Ohm\.docker\machine\cache...
(vm) No default Boot2Docker ISO found locally, downloading the latest release...
(vm) Latest release for github.com/boot2docker/boot2docker is v17.10.0-ce
(vm) Downloading C:\Users\Ohm\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.10.0-ce/boot2docker.iso...
(vm) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(vm) Copying C:\Users\Ohm\.docker\machine\cache\boot2docker.iso to C:\Users\Ohm\.docker\machine\machines\vm\boot2docker.iso...
(vm) Creating SSH key...
(vm) Creating VM...
(vm) Using switch "WebODMSwitch"
(vm) Creating VHD
(vm) Starting VM...
(vm) Waiting for host to start...
```

![image](https://user-images.githubusercontent.com/1179525/32705910-ecb95a8a-c7e6-11e7-82c4-9811b720bb52.png)

Config on WebODM Switch:
![image](https://user-images.githubusercontent.com/1179525/32705919-0b81c4f2-c7e7-11e7-83a7-4709bfc7c17a.png)
Ipconfig /all

```
C:\Users\Ohm>ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : OHM
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : Removed

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Killer E2400 Gigabit Ethernet Controller
   Physical Address. . . . . . . . . : MAC Removed
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter
   Physical Address. . . . . . . . . : MAC Removed
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : Removed(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.0.75.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter vEthernet (WebODMSwitch):

   Connection-specific DNS Suffix  . : Removed
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #2
   Physical Address. . . . . . . . . : MAC Removed
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : Removed IPV6 address(Preferred)
   Temporary IPv6 Address. . . . . . : Removed IPV6 address(Preferred)
   Link-local IPv6 Address . . . . . : Removed IPV6 address(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.107(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Sunday, November 12, 2017 7:47:33 AM
   Lease Expires . . . . . . . . . . : Monday, November 13, 2017 7:47:38 PM
   Default Gateway . . . . . . . . . : Removed IPV6 address
                                       192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : Removed
   DHCPv6 Client DUID. . . . . . . . : Removed
   DNS Servers . . . . . . . . . . . : Removed IPV6 address
                                       192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
   Connection-specific DNS Suffix Search List :
                                      Removed

C:\Users\Ohm>
```

If you need anything else, please ask.  I'm struggling to figure this out.  I had Oracle Virtual box installed and a VPN when I installed HyperV and have since uninstalled these in the prusuit of trying to figure this out. 

My PC has 2 Ethernet adapters.  One KillerE2400 and one Intel.  The Intel one is the one that is plugged into my Linksys router which is attached to my cable modem.  The config for the Intel adapter is shown below:
![image](https://user-images.githubusercontent.com/1179525/32706029-17acc366-c7e8-11e7-837d-e4a6c5865974.png)

I'm not used to virtual switches so I'm a bit out of my element.

**Comment by yosifkit** [comment] 2017-11-14 21:48
Duplicate of https://github.com/boot2docker/boot2docker/issues/1245.

**Closed** 2017-11-14 21:50 UTC
