### ISSUE TITLE
On ESXi latest version (v18.09.0) not working but v18.06.1-ce

### ISSUE THREAD

**Issue by schwankner** [boot2docker/boot2docker#1345] opened 2018-11-09 09:10 UTC
On ESXi (with latest updates Version: 6.7.0 Update 1 (Build 10302608)) using latest version of boot2docker (v18.09.0) via `docker-machine create --driver vmwarevsphere ...` the network interface card is added but no adapter type selected in ESXi and the created VM has no ip address. After manualy selecting an adapter type in ESXi I get an ip but docker deamon wont start. 

But using last stable version v18.06.1-ce with `--vmwarevsphere-boot2docker-url=https://github.com/boot2docker/boot2docker/releases/download/v18.06.1-ce/boot2docker.iso` everything works out of the box. In this version there is also no adapter type selected but nothing has to be changed.

**Comment by StefanScherer** [comment] 2018-11-11 17:01
I can see the same problem with the `vmwarefusion` driver on macOS. The `vmxnet3` NIC driver isn't loaded, there is no log message in `dmesg`.

Maybe it's related to the change to use TCL open-vm-tools 10.2.0.1608 instead of compiling open-vm-tools from stable-10.2.5 (or newer releases).

A `vmtoolsd -v` shows 10.2.0.1608 in the 18.09.0 b2d VM and it shows 10.2.5.3619 in the 18.06.1-ce b2d VM.

**Comment by tianon** [comment] 2018-11-12 20:49
Doh, good catch!  I think I've found the source of the issue (and will be making a PR shortly):

```console
$ docker run --rm boot2docker/boot2docker grep -i vmxnet /usr/src/linux/.config
# CONFIG_VMXNET3 is not set
```

**Comment by tianon** [comment] 2018-11-12 20:50
(Closing this as a duplicate of #1340 to keep the conversation in one place.)

**Closed by tianon** 2018-11-12 20:50 UTC
