### ISSUE TITLE
OS X 10.10.3 x509 certificate complaint with B2D v1.7.0

### ISSUE THREAD

**Issue by gpolyn** [boot2docker/boot2docker#939] opened 2015-06-19 02:16 UTC
Upgraded Boot2Docker on my OS X 10.10.3 and now I can't seem to use docker! I get the following:
```
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/containers/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
```

G

**Comment by rcsa-jr** [comment] 2015-06-19 05:32
same here. you can try `docker --tlsverify=false version` as a workaround

**Comment by leifhanack** [comment] 2015-06-19 07:37
Duplicate of #938

**Comment by housebolt** [comment] 2015-06-21 06:22
See #824 as well

**Comment by SvenDowideit** [comment] 2015-06-26 18:04
closing as dup of https://github.com/boot2docker/boot2docker/issues/824

note that restarting the docker daemon manually solves it, as that triggers a cert re-generation

`boot2docker ssh sudo /etc/init.d/docker restart`

**Closed by SvenDowideit** 2015-06-26 18:04 UTC
