### ISSUE TITLE
boot2docker is in violation of the pool.ntp.org terms of service

### ISSUE THREAD

**Issue by apilloud** [boot2docker/boot2docker#789] opened 2015-03-18 19:54 UTC
Boot2docker syncs time at the top of the hour and significantly increases the frequency of NTP sync by restarting ntpd hourly via a crontab. See https://github.com/boot2docker/boot2docker/blob/master/rootfs/crontab

From the Terms of Service (http://www.pool.ntp.org/tos.html):

4. End-User agrees that he or she will not:
(a) Change default settings to make more frequent request of the Services, if using an ntp daemon (“NTP Protocol”);
...
(d) Set up a regular time sync interval such as “top of the hour”, “top of the minute”, or “at minute or second X”.

**Comment by md5** [comment] 2015-03-18 20:37
Is this a duplicate of #736?

**Comment by apilloud** [comment] 2015-03-18 20:50
@md5 That issue is about the hostname used to query pool.ntp.org, this is about the frequency pool.ntp.org is queried. Related, but not the same.

**Comment by md5** [comment] 2015-03-18 20:53
I should read better next time... :eyeglasses:

**Comment by tianon** [comment] 2015-11-05 19:52
Youch.  Ok, I think we need to remove that crontab for sure now, especially since it was added before we got VBox timesync.

**Closed** 2015-11-05 19:59 UTC
